name: LANCE_GPT
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.0
  - pip=24.2
  - pip:
    - annotated-types==0.7.0
    - anyio==4.6.2.post1
    - appdirs==1.4.4
    - base58==2.1.1
    - beautifulsoup4==4.12.3
    - bech32==1.2.0
    - cashaddress==1.0.6
    - cbor==1.0.0
    - certifi==2024.8.30
    - cffi==1.17.1
    - charset-normalizer==3.4.0
    - cryptography==43.0.3
    - distro==1.9.0
    - docx2python==3.1.0
    - eth-hash==0.7.0
    - h11==0.14.0
    - html5lib==1.1
    - httpcore==1.0.7
    - httpx==0.27.2
    - idna==3.10
    - importlib_metadata==8.5.0
    - intervaltree==3.1.0
    - iocsearcher==2.4.3
    - jiter==0.7.1
    - langdetect==1.0.9
    - lxml==5.3.0
    - numpy==2.1.3
    - openai==1.55.0
    - otxv2==1.5.12
    - paragraphs==1.0.1
    - pdfminer.six==20240706
    - phonenumbers==8.13.50
    - pycparser==2.22
    - pycryptodome==3.21.0
    - pydantic==2.9.2
    - pydantic_core==2.23.4
    - pyee==11.1.1
    - pymupdf==1.24.14
    - pypdf2==3.0.1
    - pyppeteer==2.0.0
    - python-dateutil==2.9.0.post0
    - python-magic==0.4.27
    - pytz==2024.2
    - readabilipy==0.2.0
    - regex==2024.11.6
    - requests==2.32.3
    - six==1.16.0
    - sniffio==1.3.1
    - sortedcontainers==2.4.0
    - soupsieve==2.6
    - tqdm==4.67.0
    - typing_extensions==4.12.2
    - urllib3==1.26.20
    - webencodings==0.5.1
    - websockets==10.4
    - zipp==3.21.0

